<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-04-17 18:59:53                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoFbFilmDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'fb_film';
		}
		
		public function getObjectName()
		{
			return 'FbFilm';
		}
		
		public function getSequence()
		{
			return 'fb_film_id';
		}
		
		public function getLinkName()
		{
			return 'fb';
		}
	}
?>