<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-02-05 19:10:36                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoFbUserDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'fb_user';
		}
		
		public function getObjectName()
		{
			return 'FbUser';
		}
		
		public function getSequence()
		{
			return 'fb_user_id';
		}
		
		public function getLinkName()
		{
			return 'fb';
		}
	}
?>