<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-02-05 19:10:36                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoFbRoleDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'fb_role';
		}
		
		public function getObjectName()
		{
			return 'FbRole';
		}
		
		public function getSequence()
		{
			return 'fb_role_id';
		}
		
		public function getLinkName()
		{
			return 'fb';
		}
	}
?>