<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-02-05 19:10:36                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoFbActorDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'fb_actor';
		}
		
		public function getObjectName()
		{
			return 'FbActor';
		}
		
		public function getSequence()
		{
			return 'fb_actor_id';
		}
		
		public function uncacheLists()
		{
			FbRole::dao()->uncacheLists();
			
			return parent::uncacheLists();
		}
		
		public function getLinkName()
		{
			return 'fb';
		}
	}
?>