<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-04-17 18:59:53                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class FbActorRolesDAO extends OneToManyLinked
	{
		public function __construct(FbActor $fbActor, $lazy = false)
		{
			parent::__construct(
				$fbActor,
				FbRole::dao(),
				$lazy
			);
		}

		/**
		 * @return FbActorRolesDAO
		**/
		public static function create(FbActor $fbActor, $lazy = false)
		{
			return new self($fbActor, $lazy);
		}

		public function getParentIdField()
		{
			return 'actor_id';
		}
	}
?>