<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-04-17 18:59:53                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class FbFilmRolesDAO extends OneToManyLinked
	{
		public function __construct(FbFilm $fbFilm, $lazy = false)
		{
			parent::__construct(
				$fbFilm,
				FbRole::dao(),
				$lazy
			);
		}

		/**
		 * @return FbFilmRolesDAO
		**/
		public static function create(FbFilm $fbFilm, $lazy = false)
		{
			return new self($fbFilm, $lazy);
		}

		public function getParentIdField()
		{
			return 'film_id';
		}
	}
?>