<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-02-05 19:10:36                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class FbUserDAO extends AutoFbUserDAO
	{
		public function getSequence()
		{
			return 'fb_actor_id_seq';
		}
		
		/**
		 * @return FbUser 
		 */
		public function getByEmailAndPassword($email, $password)
		{
			Assert::isString($email, 'email must not be empty');
			Assert::isString($password, 'password must not be empty');
			$password = md5(FbUser::SALT.$password.FbUser::SALT);
			
			return Criteria::create($this)->
				add(Expression::eq('email', DBValue::create($email)))->
				add(Expression::eq('password', DBValue::create($password)))->
				setLimit(1)->
				get();
		}
	}
?>