<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-02-05 19:10:36                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoFbFilm extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'FbFilm', 4, true, true, false, null, null),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 128, true, true, false, null, null),
				'imdbId' => LightMetaProperty::fill(new LightMetaProperty(), 'imdbId', 'imdb_id', 'integer', null, 4, false, true, false, null, null),
				'releaseDate' => LightMetaProperty::fill(new LightMetaProperty(), 'releaseDate', 'release_date', 'date', 'Date', null, false, true, false, null, null),
				'description' => LightMetaProperty::fill(new LightMetaProperty(), 'description', null, 'string', null, null, false, true, false, null, null)
			);
		}
	}
?>