<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-02-05 19:10:36                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoFbRole extends IdentifiableObject
	{
		protected $film = null;
		protected $actor = null;
		protected $description = null;
		
		/**
		 * @return FbFilm
		**/
		public function getFilm()
		{
			return $this->film;
		}
		
		/**
		 * @return FbRole
		**/
		public function setFilm(FbFilm $film)
		{
			$this->film = $film;
			
			return $this;
		}
		
		/**
		 * @return FbRole
		**/
		public function dropFilm()
		{
			$this->film = null;
			
			return $this;
		}
		
		/**
		 * @return FbActor
		**/
		public function getActor()
		{
			return $this->actor;
		}
		
		/**
		 * @return FbRole
		**/
		public function setActor(FbActor $actor)
		{
			$this->actor = $actor;
			
			return $this;
		}
		
		/**
		 * @return FbRole
		**/
		public function dropActor()
		{
			$this->actor = null;
			
			return $this;
		}
		
		public function getDescription()
		{
			return $this->description;
		}
		
		/**
		 * @return FbRole
		**/
		public function setDescription($description)
		{
			$this->description = $description;
			
			return $this;
		}
	}
?>