<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-02-05 19:10:36                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoFbActor extends IdentifiableObject
	{
		protected $name = null;
		protected $imdbId = null;
		protected $description = null;
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return FbActor
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getImdbId()
		{
			return $this->imdbId;
		}
		
		/**
		 * @return FbActor
		**/
		public function setImdbId($imdbId)
		{
			$this->imdbId = $imdbId;
			
			return $this;
		}
		
		public function getDescription()
		{
			return $this->description;
		}
		
		/**
		 * @return FbActor
		**/
		public function setDescription($description)
		{
			$this->description = $description;
			
			return $this;
		}
	}
?>