<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-02-05 19:10:36                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class FbFilm extends AutoFbFilm implements Prototyped, DAOConnected
	{
		/**
		 * @return FbFilm
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return FbFilmDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('FbFilmDAO');
		}
		
		/**
		 * @return ProtoFbFilm
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoFbFilm');
		}
		
		public static function makeImdbUrl($imdbFilmId)
		{
			Assert::isPositiveInteger($imdbFilmId, 'imdbFilmId must be positive integer');
			
			return 'http://www.imdb.com/title/tt'.str_pad($imdbFilmId, 7, '0', STR_PAD_LEFT).'/';
		}
	}
?>